# Refresh the bundled German species names from PokeAPI's public data tables.
param([string]$SourceDirectory)
$ErrorActionPreference = 'Stop'
$baseUrl = 'https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv'
function Read-Table($name) {
    if ($SourceDirectory) {
        return Get-Content -Raw -Encoding utf8 (Join-Path $SourceDirectory $name) | ConvertFrom-Csv
    }
    return (Invoke-WebRequest "$baseUrl/$name").Content | ConvertFrom-Csv
}
$species = @{}
Read-Table 'pokemon_species.csv' | ForEach-Object { $species[$_.id] = $_.identifier }
$defaults = @{}
Read-Table 'pokemon.csv' | Where-Object is_default -eq '1' | ForEach-Object {
    $defaults[$_.species_id] = $_.identifier
}
$entries = @(Read-Table 'pokemon_species_names.csv' | Where-Object local_language_id -eq '6' | ForEach-Object {
    ,@($_.name, $species[$_.pokemon_species_id], $defaults[$_.pokemon_species_id])
})
$json = ConvertTo-Json -InputObject $entries -Compress
$output = "// Generated by scripts/update-german-names.ps1; source: https://github.com/PokeAPI/pokeapi/tree/master/data/v2/csv`n// Each entry contains the German name, species slug, and default Pokemon slug.`nconst GERMAN_POKEMON_NAMES = $json;`n"
[IO.File]::WriteAllText((Join-Path $PSScriptRoot '../public/pokemon-names-de.js'), $output)
